### ISSUE TITLE
Crash on load.

### ISSUE THREAD

**Issue by AefRal** [GeheimagentNr1/RapidLeafDecay#3]
**Versions**
Minecraft Version: 1.19.1
Minecraft Forge Version: 42.0.2
Mod Version: RapidLeafDecay-1.19.1-2.0.1

**Log files**
https://paste.ofcode.org/mivBSuLxm8ReLheTANnpuz

**Modpack**
https://www.curseforge.com/minecraft/modpacks/monumental-experience

**Describe the bug**
The game crashed whilst exception initializing level
Error: java.lang.NullPointerException: Cannot invoke "java.util.TreeSet.add(Object)" because "de.geheimagentnr1.rapid_leaf_decay.decayer.DecayQueue.decayTasks" is null
Exit Code: -1

**To Reproduce**
Steps to reproduce the behaviour:
1. Attempt to load new world.
2. Crash. 

**Expected behaviour**
Not to crash.

**Screenshots**
N/A.

**Additional context**
Your guess is... better than mine.

**Comment by GeheimagentNr1** [comment]
<table><tbody><tr><th>Status:</th><td>Won't fix (cannot be reproduced)</td></tr><tr><th>Issue type:</th><td>Bug</td></tr><tr><th>Fix type:</th><td>None</td></tr><tr><th>Fix version:</th><td>None</td></tr><tr><th>Fix release date:</th><td>None</td></tr></tbody></table>

**Issue confirmed for:**

*   None

**TODOs:**

*   [x] Test with Minecraft 1.19.1, Forge 42.0.2, Mod version 2.0.1  
    Cannot be reproduced.
*   [x] Test with Minecraft 1.19.1, Forge 42.0.9, Mod version 2.0.1  
    Cannot be reproduced.
*   [x] Test with the Monumental Experience Modpack (06.08.22, version 1.0.14, Minecraft 1.19.1) [https://www.curseforge.com/minecraft/modpacks/monumental-experience](https://www.curseforge.com/minecraft/modpacks/monumental-experience)  
    Cannot be reproduced, because the game stucks in the percent screen for creating the world, even after waiting 2-3 hours. In the log were not error messages.
